name: Auto Deploy to docs/ for GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Clean old docs/
        run: rm -rf docs

      - name: Build docs folder
        run: |
          mkdir docs
          cp portfolio-website/*.html docs/
          cp -r css docs/css
          cp -r img docs/img

      - name: Commit and Push docs/
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git diff --quiet && git diff --staged --quiet || git commit -m "CI: auto-update docs folder"
          git push
